{% set version = "2.0.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pkgcache
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pkgcache_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pkgcache/pkgcache_{{ version }}.tar.gz
  sha256: 80deafd60f15dda029536d4ce13c37ef91c49cb6636323daadbf3d64a67da028

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-r6
    - r-assertthat
    - r-callr >=2.0.4.9000
    - r-cli >=2.0.0
    - r-curl >=3.2
    - r-digest
    - r-filelock
    - r-glue
    - r-jsonlite
    - r-prettyunits
    - r-processx >=3.3.0.9001
    - r-rappdirs
    - r-rlang
    - r-tibble
    - r-uuid
  run:
    - r-base
    - r-r6
    - r-assertthat
    - r-callr >=2.0.4.9000
    - r-cli >=2.0.0
    - r-curl >=3.2
    - r-digest
    - r-filelock
    - r-glue
    - r-jsonlite
    - r-prettyunits
    - r-processx >=3.3.0.9001
    - r-rappdirs
    - r-rlang
    - r-tibble
    - r-uuid

test:
  commands:
    - $R -e "library('pkgcache')"           # [not win]
    - "\"%R%\" -e \"library('pkgcache')\""  # [win]

about:
  home: https://github.com/r-lib/pkgcache#readme
  license: MIT
  summary: Metadata and package cache for CRAN-like repositories. This is a utility package to be used by package management tools that want to take advantage of caching.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - xhochy

# Package: pkgcache
# Title: Cache 'CRAN'-Like Metadata and R Packages
# Version: 1.0.6
# Authors@R: person(given = "Gabor", family = "Csardi", role = c("aut", "cre"), email = "csardi.gabor@gmail.com")
# Description: Metadata and package cache for CRAN-like repositories. This is a utility package to be used by package management tools that want to take advantage of caching.
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# URL: https://github.com/r-lib/pkgcache#readme
# BugReports: https://github.com/r-lib/pkgcache/issues
# Imports: assertthat, callr (>= 2.0.4.9000), cli (>= 2.0.0), curl (>= 3.2), digest, filelock, glue, prettyunits, R6, processx (>= 3.3.0.9001), rappdirs, rlang, tibble, tools, utils, uuid
# Suggests: covr, debugme, desc, fs, jsonlite, mockery, pingr, rprojroot, testthat, withr
# Depends: R (>= 3.1)
# RoxygenNote: 7.0.2
# NeedsCompilation: no
# Packaged: 2020-01-30 15:10:20 UTC; gaborcsardi
# Author: Gabor Csardi [aut, cre]
# Maintainer: Gabor Csardi <csardi.gabor@gmail.com>
# Repository: CRAN
# Date/Publication: 2020-01-30 15:40:02 UTC
