{% set version = "2.2.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-pkgcache
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pkgcache_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pkgcache/pkgcache_{{ version }}.tar.gz
  sha256: fbcc976fdc8f50a5cf08591e24ca856f598070419f1d989f985c5043c55a5bc7

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-callr >=2.0.4.9000
    - r-cli >=3.2.0
    - r-curl >=3.2
    - r-filelock
    - r-jsonlite
    - r-prettyunits
    - r-processx >=3.3.0.9001
    - r-r6
    - r-rappdirs
  run:
    - r-base
    - r-callr >=2.0.4.9000
    - r-cli >=3.2.0
    - r-curl >=3.2
    - r-filelock
    - r-jsonlite
    - r-prettyunits
    - r-processx >=3.3.0.9001
    - r-r6
    - r-rappdirs

test:
  commands:
    - $R -e "library('pkgcache')"           # [not win]
    - "\"%R%\" -e \"library('pkgcache')\""  # [win]

about:
  home: https://r-lib.github.io/pkgcache/
  dev_url: https://github.com/r-lib/pkgcache
  license: MIT
  summary: Metadata and package cache for CRAN-like repositories. This is a utility package to be used by package management tools that want to take advantage of caching.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - xhochy
